# Generated by Django 6.0.5 on 2026-06-05 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
                ('public', models.BooleanField(default=True)),
            ],
        ),
    ]
