# Generated by Django 6.0.5 on 2026-06-06 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('desc', models.TextField()),
                ('points', models.IntegerField()),
                ('duration', models.TimeField()),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
